on:
  push:
    branches: ['main'] 

name: Build and Create release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          artifacts_directory: output
      - name: Get commit short SHA (release tag)
        id: shortSha
        run:
          echo "shortSha=$(git -C usr/src/rtl88x2bu rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.shortSha.outputs.shortSha }}
          draft: false
          prerelease: false
          files: output/rtl88x2bu-dkms_1.0.0_all.deb
